dist: trusty
sudo: false

addons:
  chrome: stable

language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

script:
  - npm run ci

notifications:
  slack: uni-ruse-masters:b0uEelST36eN8mkTXREAHeY0
